Run ktlint on CI
uhooi/UhooiPicBook-Android pull request #182
Opened 2021-10-07 12:38 UTC by yutailang0119

ref: https://github.com/uhooi/UhooiPicBook-Android/issues/179

Show Errors and Warnings via ktlint as Annotation on GitHub Actions.
Use [yutailang0119/action-ktlint](https://github.com/yutailang0119/action-ktlint) .

See example `Unchanged files with check annotations` in https://github.com/yutailang0119/UhooiPicBook-Android/pull/2/files

2021-10-07 15:00 UTC, uhooi requested changes

2021-10-07 15:00 UTC, uhooi commented on .github/workflows/ci.yml
> +        curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
[修正任意]
個人的には `&&` で繋げるより改行したほうが読みやすいです！

```suggestion
        curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint
        chmod a+x ktlint
        sudo mv ktlint /usr/local/bin/
```

2021-10-07 15:00 UTC, uhooi commented on .github/workflows/ci.yml
> +      continue-on-error: true
[質問]
`continue-on-error: true` は ktlint による静的解析でエラーが発生してもレポートするために付けている？
そしたら`./gradlew lint` にもあったほうがいいよね？

2021-10-07 15:13 UTC, yutailang0119 commented on .github/workflows/ci.yml
> +        curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
自分はこだわりないけど、ktlintのドキュメントはワンライナーで書いてあります
https://github.com/pinterest/ktlint#installation

2021-10-07 15:20 UTC, yutailang0119 commented on .github/workflows/ci.yml
> +      continue-on-error: true
ktlintを実行した時に、severityがerrorのものが含まれていると `exit 1` で終了します
その場合、後続に処理が続かなくなるので、 `continue-on-error: true` をつけています
他には

```bash
ktlint --reporter=checkstyle,output=build/ktlint-report.xml || true
```

でもよいです

`./gradlew` は、内部の実行をwrapするので、これのexit statusがどう解釈されるかによるけれど、 `./gradlew lint` は `exit 0` で終了しているようなので、指定していません
ktlintをGradleで実行する方法もあって、この場合は `exit 0` になるはずで、同じlint結果でも処理が継続します
https://github.com/pinterest/ktlint#-with-gradle

textlintでの例ですが、参考: https://github.com/yutailang0119/sandbox-github-actions/pull/18

2021-10-08 00:20 UTC, uhooi commented on .github/workflows/ci.yml
> +        curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.42.1/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/local/bin/
あ、なるほどです。
ただ今回は YAML で改行できるので、変えてもらえると嬉しいです 🙏

2021-10-08 00:24 UTC, uhooi commented on .github/workflows/ci.yml
> +      continue-on-error: true
なるほど、ありがとうございます！
'|| true' だとステップがエラーにならなくて CI の結果がぱっと見でわからなくなるので、このままでいいと思いますー！

2021-10-08 05:11 UTC, uhooi approved these changes

2021-10-08 05:11 UTC, merged

2021-10-08 05:13 UTC, uhooi commented
LGTM :)