dagger_hiltの導入と実行エラーの解除
uhooi/UhooiPicBook-Android pull request #74
Opened 2021-01-16 15:11 UTC by bassga

SSIA

### Question
- .ideaのディレクトリに入っているファイルの変更って入れますか？
- `app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt`で使っている`navGraphViewModels(R.id.nav_graph)`を`viewModels ()`に変更していますが大丈夫ですか？

### Subject
- DaggerHiltの導入

2021-01-17 02:36 UTC, uhooi commented
@bassga 
PR ありがとー！
Hilt どころか Dagger の知識すらほとんどないので、レビューは時間かかると思う 🙏 

気になるところ↓

- Dagger Hilt の導入で参考にした記事などがあれば教えてほしい！
- Subject は `close #71` って書いちゃっていいよ！（GitHub ではそうすると自動で PR と Issue が紐付く）
- 残タスクの 2 つ目が空欄なのが気になるｗ
- detekt（静的解析ツール）の指摘はできる限り直してほしい！  
https://github.com/uhooi/UhooiPicBook-Android/pull/74/checks?check_run_id=1714176781  
ただルールをかなり厳しくしているのですべては直さなくても大丈夫…  
ref: https://qiita.com/uhooi/items/cd1250c6f6de7d4abfd6

Question の回答↓

> .ideaのディレクトリに入っているファイルの変更って入れますか？  

仕事で Android Studio を使ったことがないから一般的なのがわからないんだよね…
DroidKaigi だとウホーイ図鑑より無視している数が多いなぁ。
`.gitignore` の修正を自分が別 PR で出すから、マージしたら `develop` ブランチを取り込み直してほしい 🙇 
ref: https://github.com/DroidKaigi/conference-app-2020/blob/master/.gitignore#L135-L156

> `app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt`で使っている `navGraphViewModels(R.id.nav_graph)`を`viewModels ()`に変更していますが大丈夫ですか？

「大丈夫」というのは「動作的に大丈夫かな？」or「動作は大丈夫だけど変更してもいい？」のどっちだろ？ｗ
後者なら OK!!

2021-01-17 02:51 UTC, bassga commented
@uhooi 
レビューよろしくお願いしまーす。

> 気になるところ↓
申し訳。。w追記とかしているなう

> 「大丈夫」というのは「動作的に大丈夫かな？」or「動作は大丈夫だけど変更してもいい？」のどっちだろ？ｗ
後者なら OK!!

動作は大丈夫だけど変更してもいい？の方！！

2021-01-17 04:51 UTC, uhooi commented
@bassga 
はーい ✋ 

>> 「大丈夫」というのは「動作的に大丈夫かな？」or「動作は大丈夫だけど変更してもいい？」のどっちだろ？ｗ
>> 後者なら OK!!
>
> 動作は大丈夫だけど変更してもいい？の方！！

それなら消してOK !!

>> .ideaのディレクトリに入っているファイルの変更って入れますか？  
> 
> 仕事で Android Studio を使ったことがないから一般的なのがわからないんだよね…
> DroidKaigi だとウホーイ図鑑より無視している数が多いなぁ。
> `.gitignore` の修正を自分が別 PR で出すから、マージしたら `develop` ブランチを取り込み直してほしい 🙇 
> ref: https://github.com/DroidKaigi/conference-app-2020/blob/master/.gitignore#L135-L156

#76 で `.gitignore` の修正 PR を出したから、 `develop` ブランチにマージしたら取り込んでくれー！

2021-01-17 04:54 UTC, uhooi requested changes

2021-01-17 04:54 UTC, uhooi commented on .idea/codeStyles/Project.xml
>      <JetCodeStyleSettings>
`.idea/codeStyles/Project.xml` はコミットしないでほしいかも！
変更する場合は理由が知りたい 🙏

2021-01-17 04:54 UTC, uhooi commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
#76 で無視するようにしたからファイルごとコミットしないでほしい！

2021-01-17 04:54 UTC, uhooi commented on .idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
[質問]
この変更ってなんだろ？

2021-01-17 04:54 UTC, uhooi commented on .idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
#76 で無視するようにしたからファイルごとコミットしないでほしい！

2021-01-17 04:54 UTC, uhooi commented on build.gradle
> +        // dagger hilt
見ればわかるコメントはなくて OK!!

2021-01-17 04:55 UTC, uhooi commented on build.gradle
> +        // dagger hilt
```suggestion
```

2021-01-17 05:13 UTC, uhooi commented on .idea/gradle.xml
> +        <option name="useQualifiedModuleNames" value="true" />
やっぱ #76 で `gradle.xml` を無視することにしたから、変更の意味は知らなくてもいいかなｗ
ファイルごとコミットしないようにしてくれれば OK!!

2021-01-17 05:23 UTC, uhooi commented
#76 マージdone 👍

2021-01-17 05:54 UTC, rmakiyama reviewed
Daggerの2.31から少し書き方も変わったのでそちらについてコメントをしました！

2021-01-17 05:54 UTC, rmakiyama commented on app/build.gradle
> +    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'
daggerのバージョンは`2.31`が先日リリースされ、APIの変更もいくつかあるので最新のを使ったほうがよさそうです！
https://github.com/google/dagger/releases/tag/dagger-2.31

またjetpackサポートの方も`alpha02`が出ているので追従しておくと良さそうです 👍
https://developer.android.com/jetpack/androidx/releases/hilt?hl=en

2021-01-17 05:54 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/MonstersModule.kt
> +@InstallIn(ApplicationComponent::class)
最新のDaggerから`ApplicationComponent`はなくなり`SingletonComponent`に置き換えが必要になりました！
ref. https://github.com/google/dagger/releases/tag/dagger-2.31

2021-01-17 05:54 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/viewmodels/MonsterListViewModel.kt
> +class MonsterListViewModel @ViewModelInject constructor(
最新のDaggerからViewModelのInjectは`@ViewModelInject`を使わず`@Inject`にし、クラスに`@HiltViewModel`を宣言する方法が推奨されているようです。将来的に`@ViewModelInject`はdeprecatedになるようなので置き換えておいたほうが良さそうです💡
ref. https://github.com/google/dagger/releases/tag/dagger-2.31

2021-01-17 12:25 UTC, bassga commented
@rmakiyama 
レビューありがとうございます！
新しいやつで対応できました。助かります！ 🙇‍♂️

2021-01-17 12:28 UTC, uhooi commented
@bassga もろもろ対応ありがとー！
自分のコメントは自分で確認してから Resolved にしたいかも！（これからでおｋ）

2021-01-17 12:29 UTC, bassga commented
@uhooi 
あ、resolvedって他の人にも反映されるんや。。。。知らんかったwww
申し訳ー！

2021-01-17 12:29 UTC, rmakiyama commented
自分のコメント部分はLTGMです！ 👏

2021-01-17 12:34 UTC, bassga commented
@uhooi 
ところでうほいほいがくれたrequested changesってどうすればいいんだろうか？

2021-01-17 12:36 UTC, uhooi commented
@bassga 
あれ実は GitHub 上でポチるだけで修正がコミットされるんだよねｗ
手動で修正してもらったから今回はもう気にしなくておｋ！

2021-01-17 12:43 UTC, uhooi commented
@bassga 
あと最新の `develop` ブランチが中途半端に取り込まれている気がする
↓を実行してはいない？
（ `origin` は uhooi のリモートリポジトリを指すとする）

```
$ git fetch origin
$ git merge origin/develop
```

2021-01-17 12:46 UTC, bassga commented
@uhooi 
あ、それやったんだけど
イグノアのやつなぜか変更入っちゃうのよね。
もう一回やってみるー

2021-01-17 12:47 UTC, uhooi commented on app/build.gradle
> +    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha01'
まきやまさん、ご指摘ありがとうございましたー！
最新の情報は全然わからないので助かります 🙏 

@bassga
ちなみに最新バージョンがあるかどうかは「Android Studio > Analyze > Inspect Code...」でわかるよー！

2021-01-17 12:49 UTC, uhooi commented
うーむなぜだろう…
オレも Git につよいわけではないからわからぬ…

2021-01-17 12:58 UTC, uhooi requested changes

2021-01-17 12:58 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
>  import androidx.navigation.navGraphViewModels
「Android Studio > Analyze > Inspect Code...」によると `navGraphViewModels` は使われていないからインポート不要とのこと！

```suggestion
```

2021-01-17 12:58 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
>  import com.theuhooi.uhooipicbook.R
「Android Studio > Analyze > Inspect Code...」によると `R` は使われていないからインポート不要とのこと！

```suggestion
```

2021-01-17 12:58 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/UhooiPicBookApp.kt
> +import dagger.hilt.android.AndroidEntryPoint
「Android Studio > Analyze > Inspect Code...」によると `AndroidEntryPoint` は使われていないからインポート不要とのこと！

```suggestion
```

2021-01-17 12:58 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/MonstersModule.kt
> +abstract class MonstersModule {
「Android Studio > Analyze > Inspect Code...」によると `MonstersModule` が使われていないと出力される…
どこで使われているんだろ？

2021-01-17 14:21 UTC, bassga commented on app/src/main/java/com/theuhooi/uhooipicbook/MonstersModule.kt
> +abstract class MonstersModule {
@uhooi 
わかんないけど、その中の処理消してみたり、ファイル消したら動かなくなった。。。。
多分だけど```app/build/generated/source/kapt/debug/com/theuhooi/uhooipicbook/UhooiPicBookApp_HiltComponents.java```
のコードを生成するためのやつだと思う。
アノテーションをみてソースコード自動生成するあれみたいな(多分)

2021-01-17 14:23 UTC, bassga commented
@uhooi 
あ、gitignoreのやつちゃんとmergeできていなかったっぽいw
申し訳ー！

2021-01-18 00:11 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/MonstersModule.kt
> +abstract class MonstersModule {
そしたらおっけー！
まだ Hilt 未勉強でレビューしているから、気になったらまた聞くかもｗ

2021-01-18 00:12 UTC, uhooi commented
強制プッシュで何とかマージしてわろたｗ
ちゃんとマージできたことを確認しました〜 🙏

2021-01-18 13:23 UTC, uhooi requested changes

2021-01-18 13:23 UTC, uhooi commented on app/build.gradle
> +    kapt 'androidx.hilt:hilt-compiler:1.0.0-alpha02'
こちらも同様！

```suggestion
    def hilt_viewmodel_version = '1.0.0-alpha02'
    implementation "androidx.hilt:hilt-lifecycle-viewmodel:$hilt_viewmodel_version"
    kapt "androidx.hilt:hilt-compiler:$hilt_viewmodel_version"
```

2021-01-18 13:23 UTC, uhooi commented on app/build.gradle
Kotlin で Hilt を使う場合は `correctErrorTypes` を `true` にしたほうがよさそう。
（よくわかっていないので違ったら指摘お願い）
ref: https://dagger.dev/hilt/gradle-setup

```suggestion

kapt {
    correctErrorTypes = true
}

```

2021-01-18 13:29 UTC, uhooi commented
`app/build.gradle` に↓の記述はなくてもいいのかな？
Java でなく Kotlin だから不要？
ref: https://developer.android.com/training/dependency-injection/hilt-android

```groovy
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```

2021-01-18 13:56 UTC, bassga commented on app/build.gradle
最初入れていて、入れなくてもビルドが通ったから消してしまっていた。。。
ガーも正直わからんがドキュメントにあるしいれよう！！

2021-01-18 14:00 UTC, bassga commented
わかんねぇ。。。。。けどドキュメントに描いてあるしいっかい入れてみて動くなら入れてみよう。。。。試す！

2021-01-18 14:10 UTC, bassga commented
```
android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
@uhooi 
こいつ入れて動いたから入れることにした。ドキュメントにあるし

2021-01-18 14:12 UTC, bassga commented
@uhooi 
> 個人的な好みだけど、バージョンを合わせる必要がある箇所は変数で定義してほしい！
これだけどそのうち`versions.xml`的なの作ってまとめて管理したいね。(今いるプロジェクトそんな感じ)

2021-01-18 14:12 UTC, bassga commented on app/build.gradle
> +
@uhooi 
これだけど2行以上ってなんかこだわりが？

2021-01-18 15:39 UTC, bassga commented on app/build.gradle
> +    kapt 'com.google.dagger:hilt-android-compiler:2.31-alpha'
> @uhooi
> 
> > 個人的な好みだけど、バージョンを合わせる必要がある箇所は変数で定義してほしい！
> 
> これだけどそのうち`versions.xml`的なの作ってまとめて管理したいね。(今いるプロジェクトそんな感じ)

https://github.com/android/sunflower/blob/ceba43e321fb9490e57a729426bb69ee59eace64/build.gradle#L26
これみたけどトップレベルの`build.gradleにまとめればいいのね。。。。`

2021-01-18 15:40 UTC, bassga commented
> @uhooi
> 
> > 個人的な好みだけど、バージョンを合わせる必要がある箇所は変数で定義してほしい！
> 
> これだけどそのうち`versions.xml`的なの作ってまとめて管理したいね。(今いるプロジェクトそんな感じ)

https://github.com/android/sunflower/blob/ceba43e321fb9490e57a729426bb69ee59eace64/build.gradle#L26
これみたけど
トップレベルの`build.gradle`にまとめればいいのね。。。

2021-01-19 00:00 UTC, uhooi commented
@bassga 
Androidの公式サンプルが、アプリレベルの `build.gradle` で使うパッケージのバージョンもすべてプロジェクトレベルの `build.gradle` にまとめているのか、、
個人的には以下のデメリットがあるから元のままに戻してほしいんだけど、どうだろう？（逆にメリットってなんだろ？）

- パッケージとバージョンの距離が離れるので、パッと見でバージョンが把握しにくい  
わざわざプロジェクトレベルの `build.gradle` に行って検索しないとバージョンが把握できない、、
- パッケージの追加や削除をするときに距離が離れていると手間になる  
削除時はバージョンの削除を忘れる可能性がある

https://github.com/uhooi/UhooiPicBook-Android/pull/74/commits/aa9e3009d24bed0638c62e1c734586b9813b1281

2021-01-19 00:45 UTC, NUmeroAndDev commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> -    private val viewModel: MonsterListViewModel by navGraphViewModels(R.id.nav_graph)
今後リリースが予定されている `androidx.hilt:hilt-navigation` を使えば元のようなコードのままにすることができそうです ☝️ 

https://github.com/androidx/androidx/commit/7bc857614c63e4cf737e0a920e62bc5d81456e22

2021-01-19 13:36 UTC, uhooi commented on app/build.gradle
> +
一画面で見れる情報を少しでも多くしたいから！
あと2行以上の空白行は1行で足りることがほとんどかな。

2021-01-19 14:02 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> -    private val viewModel: MonsterListViewModel by navGraphViewModels(R.id.nav_graph)
ありがとうございますー！
そもそも `navGraphViewModels` が何なのか思い出せません、、ｗ
通常の `viewModels` よりメリットがあるのでしょうか？

2021-01-19 15:04 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterdetail/MonsterDetailFragment.kt
> +@AndroidEntryPoint
[質問]
ここでは DI していないから `@AndroidEntryPoint` アノテーションが不要な気がするけどどうなんだろ？

2021-01-19 15:08 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/MonstersModule.kt
> +}
[質問]
このあたり全然わからんｗ
なんでシングルトンなのか、なんで抽象クラスに抽象メソッドなのかとか、、

2021-01-20 01:57 UTC, NUmeroAndDev commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> -    private val viewModel: MonsterListViewModel by navGraphViewModels(R.id.nav_graph)
Navigation のグラフ間で VM を共有したいけど Activity の VM ではスコープが広すぎる場合に使う感じですね。
今の実装みる感じは通常の `viewModels` でも特に問題はないと思います！


## 参考リンク
- https://developer.android.com/guide/navigation/navigation-programmatic#share_ui-related_data_between_destinations_with_viewmodel
- https://star-zero.medium.com/navigation-graph%E3%82%B9%E3%82%B3%E3%83%BC%E3%83%97%E3%81%AEviewmodel-8bcfebca8c13

2021-01-20 13:13 UTC, uhooi commented
@bassga すまねぇ #77 の実装によりコンフリクトが発生したから解決してほしい orz

2021-01-22 13:48 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterdetail/MonsterDetailFragment.kt
> +@AndroidEntryPoint
結論
今はおそらくいらないけど、今後 VM を DI する際に必要

2021-01-22 13:51 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/MonstersModule.kt
> +}
理解！

- `SingletonComponent` は `ApplicationComponent` が Hilt の新バージョンでリムーブ（非推奨どころじゃないｗ）されたため
- 抽象クラス + `@Binds` はインターフェースに対して DI するために必要なため
- `@Singleton` はインスタンスをシングルトンにするために付けている  
インスタンスを使い回したほうがパフォーマンスがいいらしいため

2021-01-22 13:56 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> -    private val viewModel: MonsterListViewModel by navGraphViewModels(R.id.nav_graph)
ありがとうございますー！
一般的には Activity より Navigation のほうがスコープが狭いのですね。
今回は 1 Activity 1 Navigation なので `navGraphViewModels` でも `viewModels` でも変わらない感じでしょうか。
（ `viewModels` のライフサイクルは Activity でなく Flagment 内のみ…？）

とりあえずは理解しました！

2021-01-22 14:00 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> -    private val viewModel: MonsterListViewModel by navGraphViewModels(R.id.nav_graph)
↓のリンクを見る限りでは、 `viewModels` だと Flagment 内のみで生存するっぽいですね…。
ref: https://aakira.app/blog/2020/05/dagger-hilt/

2021-01-22 14:39 UTC, uhooi commented on build.gradle
> +
```suggestion
```

2021-01-22 15:08 UTC, uhooi commented
LGTM 👍

2021-01-22 15:08 UTC, merged