Implemented licenses screen
uhooi/UhooiPicBook-Android pull request #77
Opened 2021-01-18 23:54 UTC by NUmeroAndDev

## Issue 
- close #20

## Overview
- Implemented licenses screen using [oss-licenses-plugin](https://github.com/google/play-services-plugins/tree/master/oss-licenses-plugin).

## Screenshot

|Light|Dark|
|:--:|:--:|
| ![device-2021-01-19-084946](https://user-images.githubusercontent.com/13705006/104971975-bd424180-5a33-11eb-82d4-7db92692ba2e.png) | ![device-2021-01-19-085021](https://user-images.githubusercontent.com/13705006/104971978-c16e5f00-5a33-11eb-848b-f48e91a4a987.png) |
| ![device-2021-01-19-084955](https://user-images.githubusercontent.com/13705006/104971977-c0d5c880-5a33-11eb-989c-8365151a4f76.png) | ![device-2021-01-19-085030](https://user-images.githubusercontent.com/13705006/104971979-c206f580-5a33-11eb-9a1e-ddadd927c4a1.png) |

2021-01-19 15:14 UTC, uhooi commented
うおおおお…ありがとうございます…！
Dagger Hilt の PR をマージしたら、こちらのレビューに取り掛かります 🙏

2021-01-19 15:14 UTC, uhooi commented on app/build.gradle
> +}
えっこんな書き方ができるんですか…

2021-01-19 15:16 UTC, uhooi commented on app/build.gradle
> +}
スマートでかっこいい

2021-01-19 15:16 UTC, uhooi commented
（こちらのほうがわかりやすそうだから先にレビューするかもです…ｗ）

2021-01-20 10:40 UTC, uhooi requested changes

2021-01-20 10:40 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
>      // region View Life-Cycle Methods
個人的な好みですが、 `region` コメントの下には空白行を入れたいです。

```suggestion
    // region View Life-Cycle Methods
    
```

2021-01-20 10:40 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> +    ): View {
こちらって `?` 外せるんですね…知らなかったです…。

2021-01-20 10:40 UTC, uhooi commented on app/src/main/res/menu/menu_monster_list.xml
> +<?xml version="1.0" encoding="utf-8"?>
[質問]
ファイル名を `menu_monster_list.xml` としていますが、呼び出し元のフラグメントなどに依存する命名は一般的でしょうか？
`menu_licenses.xml` でもいいと思いました。
（単に好みの問題もありそうです）

2021-01-20 10:40 UTC, uhooi commented on app/src/main/res/menu/menu_monster_list.xml
> +        android:id="@+id/action_nav_licenses"
[質問]
こちらの `id` はメニューのアイテムに対する ID なので、 `licenses_menu_item` などのほうが適切に感じますが、 `action_○○` のようにタップ時のアクションを ID にするのが一般的なのでしょうか？

2021-01-20 10:40 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> +            else -> false
公式ドキュメントによるとデフォルトで `false` を返すので、 `else` の場合は常に `false` を返しても問題なさそうですが、公式ドキュメントの通りにオーバーライド前のメソッドを呼び出すのがよさそうです。
ref: https://developer.android.com/guide/topics/ui/menus?hl=ja#RespondingOptionsMenu

```suggestion
            else -> super.onOptionsItemSelected(item)
```

2021-01-20 10:40 UTC, uhooi commented on app/src/main/res/values/themes.xml
>  <?xml version="1.0" encoding="utf-8"?>
[質問]
勉強不足で恐縮ですが、 `themes.xml` の変更で何が起きているのかわからないので、簡単に説明していただいてもいいでしょうか…？
`MainActivity` のテーマに `Theme.UhooiPicBook.NoActionBar` を指定している理由も併せてお願いします。

2021-01-20 10:41 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> +    ): View {
問題ないので解決にします！

2021-01-20 10:43 UTC, uhooi commented
@NUmeroAndDev 
レビューしました！
質問含めていくつかコメントしたので、お手数ですがご確認お願いします 🙏 

ちなみに動作はまったく問題ありませんでした！
本当にありがとうございます 😄

2021-01-20 12:01 UTC, NUmeroAndDev commented on app/src/main/res/values/themes.xml
>  <?xml version="1.0" encoding="utf-8"?>
今回導入した Plugin によるライセンス画面は Activity で表示されているので、Application の theme が適用されます。
既存のコードのままでは `Theme.UhooiPicBook` は `.NoActionBar` を継承しているのでライセンスの画面で ActionBar (Toolbar) 周りが表示されなくなってしまいます。
そのため、`Theme.UhooiPicBook` の継承元を ActionBar 付きのものに置き換え、既存の MainActivity の theme では ActionBar が表示されないように別に `Theme.UhooiPicBook.NoAcionBar` を使うようにしています。

他にもライセンスの画面 (Activity) を manifest に追加して theme を指定する方法もありますが、ActionBar なしの theme を継承して ActionBar ありの theme を作るパターンは Android アプリ開発では見かけないパターンなので、上記の変更にしています。

2021-01-20 12:42 UTC, NUmeroAndDev commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterlist/MonsterListFragment.kt
> +    ): View {
コード補完で実装した時に Nullable 扱いになっていることがあって、これは Kotlin で実装した際に Nullable かどうかを Java 側についてる Nullable/NonNull のアノテーションで判別しているので、SDK や AndroidX のライブラリ更新でアノテーションが追加されて不要になる場面もあります。

2021-01-20 13:01 UTC, uhooi commented on app/src/main/res/menu/menu_monster_list.xml
> +<?xml version="1.0" encoding="utf-8"?>
あー確かにです…。
OKです！

2021-01-20 13:02 UTC, uhooi commented on app/src/main/res/menu/menu_monster_list.xml
> +        android:id="@+id/action_nav_licenses"
あ、デフォルトが `action_○○` なのですね。
それでしたらOKです！

2021-01-20 13:08 UTC, uhooi approved these changes

2021-01-20 13:08 UTC, uhooi commented on app/src/main/res/values/themes.xml
>  <?xml version="1.0" encoding="utf-8"?>
詳細なご説明ありがとうございます…！
助かりました 🙏 
（なんで NoActionBar にしたのか思い出せない、、ｗ）

2021-01-20 13:09 UTC, merged

2021-01-20 13:09 UTC, uhooi commented
LGTM です 👍