Setup Timber #80
uhooi/UhooiPicBook-Android pull request #85
Opened 2021-01-22 02:17 UTC by omooooori

Timberでは、ReleaseビルドとDebugビルドで出力するログを切り分けられるのが大きなメリットかと思いました。
リリースログの場合、独自クラスを作る必要があったので、ReleaseLoggerクラスを作りました。

ApplicationクラスでTimberのセットアップをするのが一般的だとあったので、
MainApplicationクラスを作って、その中でTimberのセットアップをしています。

■デバックログ
　Timber.d("Debug messeage")
　Timberオブジェクトを使ってTimberのAPI（static関数）を呼び出します。

■リリースログ
　ReleaseLogger.initialize()
　ReleaseLogger.d("Release message")
　ReleaseLoggerクラスを初期化し、ReleaseLoggerクラスのstatic関数を呼び出します。

こんな感じでセットアップしてみました。

2021-01-22 02:21 UTC, omooooori commented
すみません、不慣れなものでまたdetektでCI壊してしまいました。
確認します。。。

2021-01-22 02:26 UTC, uhooi commented
全然大丈夫ですよー！
detekt のルールを厳しくしているので、緩和するのも検討しますね、、
（直せるところは直していただけると助かります）

2021-01-25 04:26 UTC, omooooori commented
CIが通るように修正しました。コードレビューお願い致します。

2021-02-26 02:46 UTC, uhooi requested changes

2021-02-26 02:46 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/UhooiPicBookApp.kt
> +            @Suppress("MagicNumber")
こちらは削除でお願いします 🙏 

```suggestion
```

2021-02-26 02:46 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/util/Logger.kt
> +package com.theuhooi.uhooipicbook.util
今のところリリース時にログを収集したくないので `Logger.kt` の実装まではしなくて大丈夫です！
ファイルごと削除してください 🙇

2021-02-26 02:47 UTC, uhooi commented
@omooooori 
遅くなりましたがレビューしました！
最新の `develop` ブランチをマージした上で、ご修正のほどよろしくお願いいたします 🙇

2021-02-26 11:56 UTC, omooooori commented on app/src/main/java/com/theuhooi/uhooipicbook/UhooiPicBookApp.kt
> +            @Suppress("MagicNumber")
了解です。削除しました。

2021-02-26 11:56 UTC, omooooori commented on app/src/main/java/com/theuhooi/uhooipicbook/util/Logger.kt
> +package com.theuhooi.uhooipicbook.util
了解です。ファイルごと削除しました。

2021-02-26 11:57 UTC, omooooori commented
> @omooooori
> 遅くなりましたがレビューしました！
> 最新の `develop` ブランチをマージした上で、ご修正のほどよろしくお願いいたします 🙇

レビューありがとうございます。
指摘事項直しました。

2021-02-26 13:21 UTC, uhooi commented
@omooooori 
ご修正ありがとうございますー！ LGTM です 👍 
コンフリクトが発生しているので、それだけ解消お願いします 🙇

2021-02-27 06:03 UTC, omooooori commented
> @omooooori
> ご修正ありがとうございますー！ LGTM です 👍
> コンフリクトが発生しているので、それだけ解消お願いします 🙇

すみません、気づきませんでした。直しました！

2021-02-27 07:42 UTC, merged

2021-02-27 07:43 UTC, uhooi commented
@omooooori 
ご対応ありがとうございますー！
マージ done