Add dancing animation
uhooi/UhooiPicBook-Android pull request #88
Opened 2021-01-25 15:04 UTC by rmakiyama

## Issue

close #9 

## Overview

Implemented cute dancing monster gif! 🎉

and add some refactoring...

- replace to ConstraintLayout in MonsterDetailFragment
- Set default Coil loader
- Use tools attributes references

## Additional

- デザインはiOS版を参考に作ったので問題があればご指摘ください🙏

## Screenshot

detail | gif detail
:--: | :--: 
![Screenshot_20210125-235922](https://user-images.githubusercontent.com/7961496/105722909-80150c80-5f69-11eb-9540-e3f47a151237.png)|![Screenshot_20210125-235925](https://user-images.githubusercontent.com/7961496/105722922-85725700-5f69-11eb-8fd5-d3cc2eb9dd73.png)

2021-01-25 15:10 UTC, rmakiyama reviewed
補足コメントをしました！

2021-01-25 15:10 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/UhooiPicBookApp.kt
> +        Coil.setImageLoader(
ref. https://coil-kt.github.io/coil/getting_started/#singleton

2021-01-25 15:10 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/UhooiPicBookApp.kt
> +                }
ref. https://coil-kt.github.io/coil/gifs/

2021-01-25 15:10 UTC, rmakiyama commented on app/src/main/res/layout/fragment_monster_detail.xml
> +        tools:text="@string/name_dummy" />
ダミーのテキストが表に出るのを防ぐ + プレビューでUIを確認しやすくするために`tools`属性を使いました！
ref. https://developer.android.com/studio/write/tool-attributes?hl=ja

2021-01-25 15:10 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterdetail/dancingmonster/DancingMonsterFragment.kt
> +        }
DialogFragmentをカスタマイズして全画面表示するための設定です。
要件を満たすための実装で1番手っ取り早かったのでDialogFragmentを採用しましたが、どうでしょう…？

2021-01-26 12:41 UTC, uhooi commented
神 PR ありがとうございます…！
これからレビューしますね！

取り急ぎ、デザインと動作はまったく問題ありませんでした！！！

2021-01-26 12:41 UTC, uhooi commented
公式ドキュメントの参考リンクが非常に助かります 🙏

2021-01-26 13:54 UTC, uhooi requested changes

2021-01-26 13:54 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterdetail/dancingmonster/DancingMonsterFragment.kt
> +        }
全然知見がないので、それで OK です！
おそらくですが、通常のフラグメントだとアクションバーなどを非表示にするのが手間なのだと予想しましたｗ

2021-01-26 13:54 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterdetail/dancingmonster/DancingMonsterFragment.kt
> +    ): View? {
ふふ…フラグメントの `onCreateView()` の戻り値の `?` は実は取れるんですよ。
私もこないだ PR で教えてもらいましたｗ

```suggestion
    ): View {
```

2021-01-26 13:54 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterdetail/dancingmonster/DancingMonsterFragment.kt
> +        view.icon_imageview.load(args.dancingUrlString)
他と同様ですｗ

```suggestion
        view.icon_imageview.load(this.args.dancingUrlString)
```

2021-01-26 13:54 UTC, uhooi commented on app/src/main/res/values/strings.xml
> +    <string name="close_button_icon_description">Close button</string>
細かいですが、、

```suggestion
    <string name="dancing_description">Dancing</string>
    <string name="close_button_description">Close button</string>
```

2021-01-26 13:54 UTC, uhooi commented on app/src/main/res/layout/fragment_monster_detail.xml
> +        tools:text="@string/name_dummy" />
`tools` 属性がビルド時に取り除かれるの、まったく知りませんでしたｗ
最高です…

2021-01-26 13:54 UTC, uhooi commented on app/src/main/res/layout/fragment_monster_detail.xml
> +        tools:src="@tools:sample/avatars" />
[修正不要]
これプレビューでいい感じに画像を表示してくれて最高ですね…
知らなかったので勉強になります！

2021-01-26 13:54 UTC, uhooi commented on app/src/main/res/layout/fragment_monster_detail.xml
> +        tools:src="@tools:sample/avatars" />
[修正不要]のコメントは読んだら Resolved にしちゃってくださいｗ

2021-01-26 13:54 UTC, uhooi commented on app/src/main/res/layout/fragment_dancing_monster.xml
> +    <androidx.constraintlayout.widget.Guideline
[修正不要]
`Guideline` 、表示されずにレイアウトのためだけに使える線ってことですね…！？
知らなかったので勉強になります 🙏 
ref: https://developer.android.com/reference/androidx/constraintlayout/widget/Guideline

2021-01-26 13:55 UTC, uhooi commented
@rmakiyama 
レビューしましたー！
お手数ですがご確認お願いします 🙏

2021-01-26 14:54 UTC, rmakiyama reviewed
丁寧なレビュー感謝です！修正します！

2021-01-26 14:54 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/UhooiPicBookApp.kt
> +        Coil.setImageLoader(
> Coil.setImageLoader() を使っている理由が気になりますー。

好みも大きいですが、アプリケーションクラスで初期化を行うライブラリは他にも多数あって、処理を他のクラスに移乗するようなパターンを使っているコードも目にします。（ref. [DroidKaigi/conference-app-2020 - App.kt](https://github.com/DroidKaigi/conference-app-2020/blob/master/android-base/src/main/java/io/github/droidkaigi/confsched2020/App.kt)）
自分では使っていませんが、Jetpackでも[App Startup](https://developer.android.com/topic/libraries/app-startup)というモノも出ているます。
それもあってインタフェースを実装する形は個人的に避けてたりします！

---

> 公式ドキュメントのように val imageLoader = ... を挟んだほうがネストが浅くて読みやすいです！

間違いないです、修正します！指摘ありがとうございます！

2021-01-26 14:54 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/UhooiPicBookApp.kt
> +                    if (Build.VERSION.SDK_INT >= 28) {
公式でも使ってますが、ここは変えたほうが良いですね…（コピペでしたすみません…！w）
サジェストありがとうございます！

2021-01-26 14:54 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterdetail/MonsterDetailFragment.kt
> +        view.icon_dancing_imageview.load(args.monster.dancingUrlString)
なるほど、Androidのプロジェクトではあまり見ないので(スコープ関数を使っている場合などは除く)、Swiftの流れかな〜くらいに思ってはいましたが、脳が無意識に`this`なしで書いちゃってました… 🙏
プロジェクトで統一するのはとても良いと思います！`README`や[`CONTRIBUTING`](https://docs.github.com/ja/github/building-a-strong-community/setting-guidelines-for-repository-contributors)等に記載されているとわかりやすいかもしれません 👍

2021-01-26 14:54 UTC, rmakiyama commented on app/src/main/res/layout/fragment_monster_detail.xml
> +        tools:src="@tools:sample/avatars" />
今回は使いませんでしたが、`@tools:sample`の中にはダミーの文字列を指定してくれるものもあるので、TextViewなんかにもたまに使ったりします！

2021-01-26 14:54 UTC, rmakiyama commented on app/src/main/res/layout/fragment_dancing_monster.xml
> +    <androidx.constraintlayout.widget.Guideline
そのとおりです！めちゃめちゃ便利です 🚀
今回は`app:layout_constraintGuide_percent`で指定しましたが、`dp`で指定することもできます 👍🏻

2021-01-26 14:54 UTC, rmakiyama commented on app/src/main/java/com/theuhooi/uhooipicbook/modules/monsterdetail/dancingmonster/DancingMonsterFragment.kt
> +    ): View? {
明示的に`NonNull`だと表明するのもよいですね、ありがとうございます！

2021-01-26 23:27 UTC, uhooi commented on app/src/main/java/com/theuhooi/uhooipicbook/UhooiPicBookApp.kt
> +        Coil.setImageLoader(
なるほど、もろもろありがとうございますー！
理由がわかったので OK です！

2021-01-26 23:30 UTC, merged

2021-01-26 23:30 UTC, uhooi commented
ありがとうございましたー！
LGTM です 👍